
server:
  port: 8888

spring:
  application:
    name: springcloud-config-server  # Confing Server  이름
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ws0110/springcloud-config  # 설정파일이 있는 깃 주소
          default-label: main # 깃 주소의 브랜치 이름
          # default-label: ENC(e8jfv1kpw9jl24kpMg80+w==) # 깃 주소의 브랜치 이름 암호화(main)
          search-paths: config-file/** # 설정 파일들을 찾을 경로
        encrypt:
          enabled: false # config(설정) 정보 암호화

encrypt:
  key: springcloud-config-enc-key  # config 정보 암호화를 위한 대칭키


# TEST URL: http://localhost:8888/app1/dev
# 암호화 URL: curl -d "Real-UserName" -X POST "http://localhost:8888/encrypt"
# 복호화 URL: curl -d "8bb17ffb18e3047bd322c681ef4f83d2f81172bf3b636624c97562b5fac8cd6f" -X POST "http://localhost:8888/decrypt"
